apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres17
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres17
  template:
    metadata:
      labels:
        role: postgres17
    spec:
      containers:
        - name: postgres17
          image: postgres:17.1-alpine
          resources:
            limits:
              memory: 600Mi
              cpu: 800m
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: 'kong'
            - name: POSTGRES_PASSWORD
              value: 'demo123'
            - name: POSTGRES_DB
              value: kong
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-postgres
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
