# Do not use Kong Ingress Controller
ingressController:
  enabled: false

image:
  repository: sazp/kong-image
  tag: '3.4.3.12'

# Mount the secret created earlier
secretVolumes:
  - kong-cluster-cert

env:
  # data_plane nodes do not have a database
  role: data_plane
  database: 'off'

  # Tell the data plane how to connect to the control plane
  cluster_control_plane: kong-cp-kong-cluster:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry:8006

  # Configure control plane / data plane authentication
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

# Enterprise functionality
enterprise:
  enabled: true
  license_secret: kong-enterprise-license

# The data plane handles proxy traffic only
proxy:
  enabled: true

# These roles are served by the kong-cp deployment
admin:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

manager:
  enabled: false
